import "./globals.css";
import React from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout component
 * @param {React.ReactNode} children
 * @constructor
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
